import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { ToastContainer } from "react-toastify";

import { yekanBakh } from "@/utils/fonts";

export const metadata = {
  title: "فروشگاه لوازم ورزشی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekanBakh.className}>
        <ToastContainer stacked theme="light" rtl={true} closeOnClick={true} />

        <main>{children}</main>
      </body>
    </html>
  );
}
