import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { ToastContainer } from "react-toastify";

import { yekanBakh } from "@/utils/fonts";
import TanstackProvider from "@/providers/TanstackProvider";
import { AuthProvider } from "@/context//authContext";
import Header from "@/layouts//Header";
import Navbar from "@/module//Navbar";

export const metadata = {
  title: "فروشگاه لوازم ورزشی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekanBakh.className}>
        <AuthProvider>
          <ToastContainer
            className="text-[#333]"
            stacked
            theme="light"
            rtl={true}
            closeOnClick={true}
          />
          <main className="w-[95dvw] max-w-[1320px] mx-auto">
            <Header />
            <TanstackProvider>{children}</TanstackProvider>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
